# Generated by Django 4.2.16 on 2024-10-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'permissions': [('pode_adicionar_produto', 'Pode adicionar produto'), ('pode_editar_produto', 'Pode editar produto'), ('pode_deletar_produto', 'Pode deletar produto'), ('pode_ver_produto', 'Pode ver produto')],
            },
        ),
    ]
