# Generated by Django 4.2.16 on 2024-09-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raro_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixinha',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
