# Generated by Django 4.2.16 on 2024-09-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raro_bank', '0003_alter_caixinha_objective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixinha',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
