# Generated by Django 4.2.16 on 2024-09-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raro_bank', '0005_alter_caixinha_name_alter_caixinha_objective_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixinha',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='caixinha',
            name='objective',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='caixinha',
            name='value',
            field=models.FloatField(),
        ),
    ]
