# Generated by Django 4.2.16 on 2024-09-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raro_bank', '0006_alter_caixinha_name_alter_caixinha_objective_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixinha',
            name='value',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
