# Generated by Django 4.2.16 on 2024-09-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raro_bank', '0008_alter_caixinha_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixinha',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
