# Generated by Django 4.2.16 on 2024-09-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raro_bank', '0012_alter_caixinha_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixinha',
            name='value',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
