# Generated by Django 4.2.16 on 2024-09-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raro_bank', '0015_alter_caixinha_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixinha',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
